services:
  backend:
    build: ./backend
    command: "npm start"
    expose:
      - "5000"
    volumes:
      - backend-node-modules:/app/node_modules
      - ./backend:/app
    environment:
      NOTION_SECRET: ${NOTION_SECRET}
      NOTION_DB: ${NOTION_DB}
  frontend:
    build: ./frontend
    command: "npm start"
    ports:
      - "${PORT:-3000}:3000"
    environment:
      REACT_APP_API_URL: "http://backend:5000"
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app

volumes:
  frontend-node-modules:
  frontend-app:
  backend-node-modules:
  backend-app:
